version: '3'
services:
  proxy-service:
    container_name: proxy-service
    image: akhmet_tolegen/proxy-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"