basePath: /v1
definitions:
  v1.response:
    properties:
      error:
        type: string
    type: object
  v1.taskByIdResponse:
    properties:
      headers:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      httpStatusCode:
        type: integer
      id:
        type: string
      length:
        type: integer
      status:
        type: string
    type: object
  v1.taskCreateRequest:
    properties:
      body: {}
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      url:
        type: string
    type: object
  v1.taskCreateResponse:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
  description: Proxy service
  title: Proxy API
  version: "1.0"
paths:
  /task:
    post:
      consumes:
      - application/json
      description: Create task
      parameters:
      - description: Request
        in: body
        name: CreateRequest
        required: true
        schema:
          $ref: '#/definitions/v1.taskCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.taskCreateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      tags:
      - Task
  /task/{id}:
    get:
      consumes:
      - application/json
      description: Get task by id
      parameters:
      - description: Task id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.taskByIdResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      tags:
      - Task
swagger: "2.0"
